version: ‘3’

services:
  redis:
    image: redis
    tty: True
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - custom

  web:
    build: .
    tty: True
    ports:
      - '8000:80'
    depends_on:
      - redis
    networks:
      - custom
    env_file:
      - ./.env.docker

volumes:
  redis-data:

networks:
  custom:
    driver: bridge
